spring:
  application:
    name: Expense-Tracker-API
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:expense-tracker-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:7h3mb3la}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:YTNmOGMyZDFlNGI3MDkxZjZhMmM1ZThkM2I0ZjdhMWMyZTVkOGIzZjZhOWMyZTVkOGIxZjRhN2MwZTNkNmI5}
      access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
      refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
      issuer: ${JWT_ISSUER:Expense-Tracker-API}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    doc-expansion: list
    tags-sorter: alpha